<?php include("/home/.saffron/ocbabe/oc-obsessed.com/header.php"); ?>

<h1>&gt; &gt; actors</h1>

<p>Here's all the information you want to know about the actors on The O.C.</p>

<p><b>Adam Jared Brody</b> (born December 15, 1979 in San Diego, California) is an American actor. He currently stars in the American TV series The O.C., where he plays the character Seth Cohen, a geeky and slightly awkward seventeen year old. He grew up in San Diego, but moved to Hollywood in 1999 and hired an acting coach and quickly signed with a manager. A year of living in Hollywood he landed the role of Barry Williams in Growing up Brady. He landed recurring roles on Gilmore Girls and the Canadian comedy television series Sausage Factory. In 2003 he played his most famous role to date, Seth Cohen on The O.C. He is currently engaged to O.C. co-star Rachel Bilson. Brody appeared as Benjamin alongside Angelina Jolie and Brad Pitt, in Mr. and Mrs. Smith, his biggest movie role to date. He also plays drums for the band Big Japan. <a href="/actors_adambio.php">Find out more...</a></p>

<p><b>Benjamin McKenzie Schenkkan</b> was born and raised in Texas. Following, his graduation from the University of Virginia where he was a Foreign Affairs and Economics major, he moved to New York to pursue his passion for acting. While in New York, he appeared off-Broadway in "Life is a Dream" at the Soho Rep. Additionally, he performed in numerous productions at the Williamstown Theatre Festival, including "Street Scene" and "The Blue Bird," and at the University of Virginia, in "Measure for Measure" and "Zoo Story" before moving to Los Angeles where he landed a lead role in THE O.C. <a href="/actors_benbio.php">Find out more...</a></p>

<p><b>Kelly Rowan</b> (born 1967 in Ottawa, Ontario, Canada) is a Canadian actress well known for her twenty-five years in the industry, most recently for her role as Kirsten Cohen on The O.C. Rowan began her career in 1980. She graduated from Northern Secondary School in 1985. She is also a graduate of the University of Western Ontario. Appearing in movies such as The Gate, Hook, Three to Tango, and A Girl Thing, Rowan remained a recognisable face without a well-known name for years, guest starring in television shows such as The Outer Limits, Da Vinci's Inquest, CSI: Crime Scene Investigation and Dallas. In 2002, Rowan guest starred in three episodes of Boomtown, playing Marian, the cuckolded wife of David McNorris (Neal McDonough). She returned for one last episode in 2003. That same year, she was cast as Kirsten Cohen on the new FOX program, The O.C. alongside Peter Gallagher, Tate Donovan, Adam Brody and Melinda Clarke, who had appeared on the same episode of CSI. The show has enjoyed two successful seasons and will begin its third in the fall of 2005. <a href="/actors_kellybio.php">Find Out More...</a></p>

<p><b>Melinda Clarke</b> (born April 24, 1969) is an American actress who has worked on television series and independent films. Clarke appeared in the daytime soap opera Days of Our Lives (where her father, John Clarke was a senior cast member), and starred on Soldier of Fortune, Inc. for both of its seasons. She also guest starred on Xena: Warrior Princess, Firefly, and had a memorable two episode stint on CSI. Coincidentally, one of her appearances on CSI was with Kelly Rowan, who would later be her co-star on The O.C. She appeared as a guest star on the FOX drama The O.C., and due to fan response Clarke was offered a contract for her role as Julie Cooper, a cunning socialite who marries for money. Clarke accepted the role and has since become an integral part of the show's success. She is married and has a daughter, Kathryn. She resides in Beverly Hills, California. <a href="/actors_melindabio.php">Find out more...</a></p>

<p><b>Mischa Barton</b> was born in London, England, but moved to New York when she was four years old. Her mother’s name is Nuala. She has two sisters, Hania and Zoe. Barton is half English and half Irish. Barton also lived in Ciudad del Este, Paraguay from 1991 to 1993, where her mother worked for the Peace Corps. Barton still claims Asunción, Paraguay is one of her favorite spots for a relaxing vacation, where her anonymity is maintained. Barton graduated from the Professional Children's School in Manhattan in 2004. She claimed that after graduating high school, she hoped to attend the Yale School of Drama. She's been romantically involved with on again, off again boyfriend oil heir Brandon Davis. <a href="/actors_mischabio.php">Find out more...</a></p>

<p><b>Peter Gallagher</b> (born August 19, 1955 in Armonk, New York) is an American actor who currently stars as Sandy Cohen, a public defender and corporate lawyer, on the Fox television show The O.C.. He has recently become quite well-known, as his trademark is his large bushy eyebrows. He now hosts an annual award ceremony named "The Sandy Cohen Awards", or The Sandys, which in honor of his character now give a scholarship to a law school student at UC Berkeley who wants to become a public defender. <a href="/actors_peterbio.php">Find out more...</a></p>

<p><b>Rachel Bilson</b> (born Rachel Sarah Bilson on August 25, 1981 in Los Angeles, California) is an American actress. She is the grandaughter of director Bruce Bilson and the daughter of writer/director Danny Bilson. Her stepmother is Heather Medway, an actress and the mother of Rachel's two-year-old half-sister Hattie. She graduated from Notre Dame High School in 1999 where she appeared in such productions as Bye Bye Birdie, Once Upon a Mattress and The Crucible. In addition to her role on the OC, she has appeared on shows such as 8 Simple Rules for Dating My Teenage Daughter, Buffy the Vampire Slayer, That '70s Show, and Punk'd after being tricked by Ashton Kutcher for the havoc caused by the dog that was also owned by O.C. co-star/boyfriend Adam Brody. She resides in a two-bedroom condo in the Hollywood Hills that has been in her family for years with her best friend Leah. She is currently dating and engaged to fellow O.C. actor Adam Brody. <a href="/actors_rachelbio.php">Find out more...</a></p>

<p>Thanks to <a href="http://www.wikipedia.org">Wikipedia</a> for actor information!</p>

<?php include("/home/.saffron/ocbabe/oc-obsessed.com/footer.php"); ?>