<?php include("/home/.saffron/ocbabe/oc-obsessed.com/header.php"); ?>

<h1>&gt; &gt; the oc effect</h1>

<p>Thanks to <a href="http://www.popmatters.com/">popmatters.com</a> for this great <a href="http://www.popmatters.com/music/features/050114-indiesoundtracks.shtml">article</a></p>

<p>Every good movie director has a composer that they can depend on to score a dynamite soundtrack that will not only bolster their film but will roll off the shelves into the eager hands of film fans willing to spend more than just the ticket price. Steven Spielberg has John Williams. Tim Burton has Danny Elfman. And Zach Braff has, well, James Mercer of the Shins. Actually, Mercer didn't exactly score Braff's filmmaking debut, the 20-something-friendly Garden State, but he agreed to let Braff feature not one but two Shins songs from their debut album, Oh, Inverted World. Braff, who lists the Shins as his favorite band, not only featured a double dose of Oh, Inverted World in Garden State, but also had Natalie Portman's character telling his character that the Shins will change his life. Actually, it's more like he changed their life. The result? Album sales for Oh, Inverted World have tripled since the film's release in August, and the Shins have become a household name alongside more well-known indie acts like the Flaming Lips and Wilco.</p>

<p>Indeed, in the last year, more and more indie bands have made their way into the mainstream through movie soundtracks, television appearances that are written into the plots of the shows and, most important, Fox's The O.C., a show whose characters may be a bit trashy but whose writers seem to have impressive musical taste. This sudden upsurge of music that is-- gasp! -- considered to be good in the eyes of elitist hipsters and rock critics alike is surprising, proving extremely beneficial to bands like the Shins and Death Cab for Cutie in terms of exposure -- and cold hard cash. It seems like a winning formula for all parties involved, except for the original fans, who smell sell out. But ultimately, with more and more music fans recognizing bands that would otherwise garner little or no attention, why can't these diehard fans be happy for Death Cab and the Shins' success?</p>

<p>The recent surge of indie bands gaining recognition via participation in the plotlines of a television show started last year, when two characters on The O.C. began arguing about Death Cab for Cutie while listening to one of their songs. One of the characters, Seth, says &quot;Don't dis the Death Cab.&quot; Viewers at home agreed. Since then Death Cab has sold almost two hundred thousand copies of 2003's Transatlanticism, and, recently, got themselves signed to a major label, Atlantic.</p>

<p>Death Cab is the most famous instance of what I'll call The O.C. effect, but dozens of other relatively unknown bands have crept onto the show's soundtrack over the last year. Pop rockers Rooney made the sole live appearance on the show last season and saw a near tripling of their album sales. And this season, the Walkmen, the Killers, Modest Mouse and the Thrills will all get their chance to pretend to strum their guitars in front of Mischa Barton.</p>

<p>In November, The Walkmen appeared live on the show, playing two tracks off its album Bows & Arrows. Singer Hamilton Leithauser enjoyed his experience filming the show, though he felt that the staged enthusiasm for the band was a bit much. &quot;There were maybe two hundred extras on the set pretending to just love us, and I had to sing along with the music, and of course everyone else is fake playing -- they're not even plugged in,&quot; Leithauser said. &quot;So it was really an awkward scene for me, but I think you're just supposed to stand there and look cool anyhow, so I just tried to do that.&quot;</p>

<p>Leithauser, who was surprised the show allowed the Walkmen to play two songs, sees television performances as a solid, if ephemeral, means of promotion. &quot;I don't think we'll gain fans,&quot; Leithauser said. &quot;I think people will buy the record though. I think a lot of people bought the record after we were on Dave Letterman and Conan, but I don't think you can really gain actual fans who are going to really care about the band through such a mass-market thing.&quot;</p>

<p>Shawn Rogers, the creative director of film and TV licensing at Sub Pop finds The O.C. to be highly beneficial for his label's bands. &quot;We've had a couple of bands appear on The O.C.,&quot; Rogers said. &quot;I think it's great that indie bands are on the show. It pays well in comparison to what most indie bands make touring or selling records and the creator of the show loves that style of music.&quot;</p>

<p>The Shins, who appeared live on The Gilmore Girls last season, might also beg to differ with Leithauser. After all, it took only one well-connected Shins fan to spread the gospel of the indie &quot;it&quot; band. Shins frontman James Mercer, who joked that Braff &quot;obviously has impeccable taste,&quot; was pleased with the way the film turned out and even more pleased by how much the film has bumped the Shins into people's consciousness. &quot;I guess you certainly feel flattered,&quot; Mercer said. &quot;It's helped a lot. The only sign I have is that Sub Pop calls me and tells me the records are selling better. Especially Oh, Inverted World, which was sort of falling off the radar for most music listeners and now is selling better that it actually ever sold.&quot;</p>

<p>Sam Beam, the mastermind behind Iron & Wine, agreed that the use of his music in Garden State was flattering. Beam covered the Postal Service's infectious &quot;Such Great Heights&quot; for the soundtrack. He says that all opportunities for exposure are worth pursuing: &quot;Any chance you get, any forum to put [your music] out to people other than just people who go to the record store,&quot; he explained. &quot;Indie bands don't get on the radio very much. I think there's one station out in Los Angeles now. But other than that all they have is the Internet, that kind of a forum. So anything extra is great.&quot;</p>

<p>Of his song's appearance in the film, the Postal Service's Jimmy Tamborello said he's &quot;glad it wasn't our version. When I went to see the film I got really nervous for it to come on. I think it would have been more nerve-racking if it was our version.&quot; But despite Tamborello's anxiety, which is funny sentiment considering how one assumes musicians want to get their music into the public sphere as much as possible, the Postal Service contributed a song to the soundtrack for the film Wicker Park, which also featured the Shins, Death Cab for Cutie, and Mates of State. &quot;It's nice whenever anybody invites you to be a part something,&quot; Tamborello said. &quot;I mean, I haven't seen this movie, but it's great when it's a movie that you like. It's definitely a good way [for indie bands to gain exposure]. I think people at the movies, when they like a song, they'll wait 'til the credits to find out what it was. And it gets heard by people who maybe aren't even big music fans, who wouldn't find it otherwise.&quot;</p>

<p>Mercer noted that he initially didn't want the Shins to contribute their b-side &quot;When I Goosestep&quot; to the Wicker Park soundtrack because he feared an oversaturation of the soundtrack market, a market that may be very different for the one that initially bought Shins records. &quot;We started worrying that people were going to be able to buy our music so easily elsewhere that there would be no reason to buy Shins records and see [the songs] in the context of a Shins record,&quot; Mercer said.</p>

<p>Though the O.C. Effect seems overwhelmingly beneficial to bands like the Shins, Mercer's point is key. By allowing their music to be placed in a situation external to a Shins album or concert, the band relinquishes a sense of control to that external medium. The creative control is now in the hands of the filmmaker (in the case of Garden State) or the directors of The O.C., who can place the song in a context that can potentially alter the band's intended meaning of the song. However, the fact that Tamborello hasn't even seen the movie in which his song is featured suggests that some bands may not even care. It is certainly a drawback that artists lose creative control, as Mercer points out, but one that doesn't seem to be stopping bands from offering their work to these movies and shows.<p>

Instead, in the past few months bands have been avoiding the issue by contributing new, "themed" songs to movie soundtracks- case and point The SpongeBob SquarePants Movie soundtrack. This children's movie ended up boasting one of the best movie soundtracks this year, with original songs from the Flaming Lips, Wilco, the Shins, and Motorhead. Tweedy, who claimed that contributing to this soundtrack "automatically makes [him] the coolest dad on the block," wrote the song specifically for the film.

The latest buzz in the soundtrack world comes from a video game. The soundtrack to the forthcoming Stubbs the Zombie game features new songs from Ben Kweller, Rogue Wave, the Ravonettes. Rather than writing original tracks for the album, each band was asked to reinvent an old favorite. So you have the Flaming Lips singing "If I Only Had a Brain" and Kweller singing "Lollipop" -- something that may indicate what direction this trend will take next.

So why are so many directors and music supervisors turning to lesser known acts to fill their films and television shows with music that would otherwise probably not get heard by the majority of their viewers? Rogers thinks it because a different generation of filmmakers is now in control of the screen. "You are seeing more and more indie music appearing in films, television and ads because there is a generation of film directors, TV producers, and creatives at ad agencies that are finally in positions of employment to support bands and the style of music that they've been following for the last ten to twenty years," he explained.

Tamborello has a slightly different theory: "Part of it could just be financial -- we're cheaper. Also, the people that are making movies and TV shows are artists, and maybe they are just more likely search harder for music that they like and they might find a song they want to share."

It seems like a win-win situation all around, but how come some fans and critics are calling foul, stating that such appearances and mass marketing techniques are creating sell-outs? When virtually everything can be construed as promotional, what does selling out even mean?

Emily Haines, whose band Metric made an appearance in the French-Canadian film Clean earlier this year, feels that the term "selling out" has become meaningless, because the line one must cross is so subjective. "I guess everyone has their own measure of what they're willing to do and what they're not," Haines explained. "For me it would totally depend on the [TV] program. I think it's clear that everyone's sort of changed their standards of what they're willing to do. Things that used to be considered selling out don't seem to be anymore, so I don't know if that's depressing or if that means we're more open-minded." Haines does feel, however, that a band's onscreen promotion should have its limits. "Some people will always argue that any exposure is good, but I don't agree," Haines said. "It's just all about the context I would think. Having your song on a horrible film, that's not gonna do you any favors."

Mercer is mildly concerned about the reaction of his devoted fans to the Shins' soundtrack hopping: "I had wondered what will be the real Shins fans' perception of the band if we were as big as Modest Mouse or something -- which is unlikely to happen. I hope that our audience is more sophisticated than I was when I was a teenager, where I would probably drop a band if my sister knew about them. If my sister knew about the band then they weren't cool anymore."

When asked what he would say to someone who accusing the Walkmen of selling out for their appearance on The O.C. Leithauser simply said: "I'm not sure what I'd say . . . maybe 'fuck you.' " That seems to be the most apt answer to the inevitable questions that are sure to follow such an appearance, especially since indie bands on mainstream TV shows and movies sounds far better than the status quo.

<?php include("/home/.saffron/ocbabe/oc-obsessed.com/footer.php"); ?>