<?php include("/home/.saffron/ocbabe/oc-obsessed.com/header.php"); ?>

<h1>&gt; &gt; editing the oc</h1>

<p>A TV show takes a lot of time and work to before it airs on a TV screen near you. There is a lot of pre-production that goes from writing the episode, to casting, to scouting locations, etc., but also a lot of post-production. Once the episodes are shot, the editor must go through all the reels and cut it out, add the music, and much more, before it’s ready to air. Norman Buckley is one of THE O.C.’s editor and agreed to tell us more about what an editor does and how an O.C. episode comes to life.</p>

<p>According to the &quot;Norman Buckley Dictionary,&quot; an editor is the surrogate for the audience. &quot;Amongst all the footage that is shot for a particular episode, it is the editor’s job to decide what is the most important thing to be looking at in any given moment – what does the audience want to see NOW. A director’s choices, as to what he shoots, will often dictate the cuts, but since the directors are rotating week after week, it falls to the editors to maintain the stylistic consistency of the show,&quot; he revealed.</p>
	
<p>Norman Buckley first intended to become a writer. He joined USC Film School where students were encouraged to develop a craft as well as writing. Since he was a middle-class kid going to a rich kid’s school, he needed to find a craft that would allow him to work when he was free as he was already working part-time on three jobs to pay for school. Buckley took on editing as he could do it on his own time, his own schedule, and didn’t have to worry about anyone else’s schedule. He took editing like a duck to water and had a natural aptitude for it.</p>
 
<p>It wasn’t easy for Buckley to venture into the film industry as his father thought it was a waste of time. &quot;Both of my brothers are engineers, which he thought was a more worthy endeavor. Fortunately, my father expressed his pride in my accomplishments before he died.&quot; His father may not have been the biggest show business fan, but his mother loves it!</p>

<p>His sister, Betty Buckley, is known for her Broadway acts but most may remember her as Suzanne Fitzgerald from the HBO series OZ. When asked why he didn’t follow in his sister’s footsteps, Norman Buckley reveals that he never had the desire to perform. &quot;I think it’s much more fun to watch than to be watched,&quot; he says. Besides his sister and he being in the industry, one of his brothers was married to a successful New York actress and their daughter, Erin, is in her second year at the Yale Drama School.</p>

<p>Norman Buckley’s first editing job was on the 1983 movie TENDER MERCIES starring his sister and Robert Duvall. The movie was shooting near his hometown in Texas. He got the job because his sister heard the editor was looking for a local assistant. &quot;I asked the editor to take me to New York with him to complete the film if I did a good job. He did and that was how my career began,&quot; he reveals.</p>

<p>Even though he said he had no interest in becoming an actor, Buckley played &quot;Israelite #1&quot. in SOLOMON & SHEBA starring Halle Berry. &quot;I was editing a movie in Morocco. The producers were shooting a second movie at the same time and didn’t want to fly any more actors to location. It was only one line.&quot; He even admits he tried to get the mention of the role off his <a href="http://www.imdb.com">IMDB.com</a> profile as it looks like he had a miserable failed acting career when, in reality, he never had any desire to act.</p>

<p>Norman Buckley edited movies, TV movies, and TV series, with small and big budgets. Even if every project holds its own challenges and opportunities, he prefers TV. &quot;I find television the hardest – the schedules are tough and relentless – but also I find television the most satisfying because when it’s good and successful, as THE O.C. has been, it’s extremely exhilarating to work so hard and have people be so passionate about it. This has been my favorite job of my entire career.&quot;</p>

<p>Talking about THE O.C., how did he get such a cool job? &quot;My involvement came through my very great relationship with McG’s company, Wonderland Sound and Vision. I met McG and Stephanie Savage a couple of years ago. I edited the pilot of FASTLANE and then did the series. McG originally intended to direct the pilot of THE O.C. but his responsibilities on CHARLIE'S ANGELS 2 precluded that. I had already been offered the job of editing THE O.C. pilot, so when Doug Liman took over, they told him I was part of the package. I got along very well with Doug, who shot the pilot and the first episode, 'The Model Home.' But the more significant collaboration has been my relationship with Josh Schwartz – I like being part of HIS vision. He is the reason I’m here and enjoying this job so much!&quot;

<p>On THE O.C., Norman Buckley is co-editor with Matt Ramsey. The two met each other when Buckley hired Ramsey several years ago as one of his assistants on a feature he was working on in North Carolina. Ramsey continued as his assistant on several projects. &quot;When I edited FASTLANE, I asked that he be bumped up to editor. When I was offered THE O.C., I asked Matt to join me on this show.&quot; Buckley edits every other episode and Ramsey does the others. Matt Ramsey edited the pilot of THE MOUNTAIN but decided to come back to work on THE O.C. second season instead of sticking with The WB show.</p>

<p>It takes a lot of people to edit one episode of the hit FOX series. &quotlThe two of us have three assistants who rotate on the shows. We also try to give the assistants opportunities to cut an episode of their own (two of them cut one episode each last year). We also have an associate producer who is in charge of budgeting, logistics, and finishing. There is a post-production supervisor who is in charge of scheduling. Finally, there is a post-coordinator who liaisons with other departments. We’re a very happy group – we’re all great friends and it’s an extremely supportive environment.&quot;
It takes eight days to shoot an episode of THE O.C. Editors start putting the material together on the second day after shooting began and have until two or three days after the completion of filming to edit the episode. Once this is done, the director has two to four days to sit with the editing team and to collaborate on a cut the he is happy with. &quot;At that point, Josh Schwartz and Bob Delaurentis come into the editing room to give us their notes – that usually takes a day or two, then we send the show to the network and they give us notes that they may have. After we finish a cut that we’re all happy with, we 'spot' the show with our composer and sound editors – that means we go through the show with them, indicating where and how we want sound and music. After they work on the show for a week to ten days, we mix the show on a dubbing stage with sound recordists, so that it sounds as good as possible.&quot;</p>

<p>The two editors are given an enormous amount of freedom as regards to the music of the show. They are encouraged to try things. The show’s music supervisor, Alexandra Patsavas, sends them a CD every week with 15 or so songs by new bands that she thinks would be right for the show. They try different things. &quot;For instance, in the episode 'The Secret' from last year, I loved this one song 'We Used to Be Friends' by The Dandy Warhols on one of the CDs that Alex had sent us. I had the idea to use it as a repeating motif throughout the show, and that became a decide that we have frequently used since. We’ll find a song that plays thematically – and that song will be used to tie several scenes together.&quot; Even if they have freedom concerning the soundtrack, Josh Schwartz is the one making the finale decisions. &quot;Josh is the truest and best of colladorators and he gave Matt and me a lovely tribute in the liner notes of the Mix 2 CD,&quot; Buckley reveals.
When they can’t find the right song to go along with a scene, the editors put the scene on tape and send it to the Music Supervisor’s office so she tries to find the best song.</p>

<p>As for the scored music, Ramsey and Buckley put in temp tracks (music from other shows or movies) in order to give THE O.C. composer, Chris Tyng, an idea of what the final product should sound like. &quot;For the Pilot, I originally used a lot of temp music from AMERICAN BEAUTY and WHITE OLEANDER, both scored by Thomas Newman, one of my favorite composers. If you know music, you can hear the influences of those scores in some of Chris’ music, but he has brought his own unique vision to the table as well.&quot;</p>

<p>When working with the composer, Buckley enjoys the discussions they have about what they’re trying to achieve with a piece of score. &quot;Is it moving a scene along so that it doesn’t feel slow? Is it trying to make you feel what a character is thinking or feeling, but not saying? Is it setting up a joke? All these questions are things we try to discuss and figure out,&quot; the editor says.</p>

<p>One of Norman Buckley’s favorite pieces of music on the show is what they call the &quot;Ryan/Marissa Love Theme.&quot; It is the piece of music that played under the scene where Ryan and Marissa first meet in the Pilot, where he lights her cigarette. &quot;It has a beautiful, lonely piano line that establishes immediately that this is an important relationship for both of them – it sets up a mythic component to their romance. The piano in the piece doesn’t start the major melody line until the very moment he lights her cigarette – that first moment where they actually connect,&quot; he says about his favorite piece. &quot;It’s not a sentimental piece of music, but nevertheless, the chords are deeply beautiful, and every time that music plays it evokes what Ryan felt at the very first moment he met Marissa,&quot; he adds.</p>

<p>Another of his favorite pieces is the &quot;Julie Cooper Theme,&quot; which is another of the very powerful musical motifs the editors frequently return to. The &quot;Julie Cooper Theme&quot; first played in the episode &quot;The Outsider,&quot; an episode where she expresses her vulnerability to Kirsten in the limo. &quot;We use that theme in many places throughout the episodes, not just with Julie, but with characters who may be talking about Julie. I think it works because it suggests that Julie isn’t all bad. She’s a complicated character – the music suggests aspects to her personality that go beyond her mean-spiritedness.&quot;</p>

<p>Another theme that was developed over several episodes is the one that is tied to Teresa. &quot;There is a scene in the first episode of the second season that is kind of a summation of all the music that has come before relative to her character, and it expresses the pain that Teresa feels, in spite of what she’s saying. It plays counterpoint to her behavior, and thus, let’s us know what she’s really feeling. It’s beautifully done and I think it’s one of the best things that Chris Tyng has done on the show.&quot;</p>

<p>As he edits an episode, it is possible he finds that a scene isn’t working out. &quot;The question is always ultimately – what is the purpose of the scene?&quot; If he can’t figure it out the purpose of a scene in the story, the he must try to fix it. Fixing it may be deleting it or rewriting new dialogue that might play off camera on another character’s face. &quot;We have, on a few rare occasions, gone back and reshot scenes to make certain things play better. The Palm Springs episode last year was rewritten after we’d looked at the first cut. Originally, the audience didn’t know whether Oliver had attempted suicide or not, but we decided that the suspense would be heightened if the audience knew information that Ryan and Marissa did not. I think it was the right decision – it made the episode stronger and increased sympathy for Ryan, though it seemed to make Marissa much less sympathetic in the eyes of the audience.&quot;</p>

<p>Another reason why scenes are cut is because of time constraints. The decision of which scenes to remove to make the episode just the right length falls on the shoulders of the editors, Josh Schwartz and Bob Delaurentis. The director will often weigh in, but he is usually not around at the point that these decisions are made. However, producing director, Ian Toynton, often sits in those meetings as he was hired to help maintain a stylistic consistency. Toynton also directed two episodes of season one.</p>

<p>Some of the actors do hang out in the editing room and give their ideas: &quot;We’re all a very friendly group and the actors seem to enjoy coming by and hanging out in the editing room. They are all extremely deferential, never trying to exert their will, but they frequently will have great ideas, remember takes where they did something that we might have missed. They are a great bunch – they ask all the right questions and trust us to do our very best by them. I like the entire cast very much,&quot; Buckley adds.</p>

<p>The editors job is to also keep track of all deleted scenes as some of them will end up on the DVDs. At the end of the first season, one of Buckley’s assistant assembled all of the deleted scenes and then, the editor went back through them and polished them up.
All in all, it takes about twenty days to edit an episode of THE O.C. This number of days can fluctuate, as they get closer to the airdates. At the moment of this interview (late October 2004), they already had six episodes completed for the second season even before the season premiere aired on FOX. &quot.Because we are doing 24 episodes this year, our schedule will become very compressed and it is likely to get pretty frantic as the year goes on.&quot;</p>

<p>This year, along with teaching part-time at the UCLA graduate level and doing his editing job on the show, Norman Buckley is set to direct his first episode of THE O.C. It will be the 18th episode out of the 24 FOX ordered. &quot;I’m hoping it will be the first of many,&quot; he mentions. &quot;I’m content to be working here – great job, great people. It all comes down from the top – Josh Schwartz is a remarkable guy. He’s generous, encouraging, collaborative, but also very clear about what he wants. He gives us a vision we can all focus on. I’m really glad I’m on his team.&quot;</p>

<?php include("/home/.saffron/ocbabe/oc-obsessed.com/footer.php"); ?>